### ISSUE TITLE
More descriptive column names

### ISSUE THREAD

**Issue by boz** [laurengordonfahn/simple_notebook_project#1]
* `Notes` model:
  - [ ] rename `date_at` column to `created_at`
  - [ ] rename `note` column to `content`

**Comment by laurengordonfahn** [comment]
In changing two simple words, I learned that I must be very aware of every aspect that could draw on those words. I missed editing my jinja templating in my index.html and just spent an hour debugging, I learned a ton about my project from this little edit!

**Comment by boz** [comment]
:) yes that's part of the point of going through this.

Next time do the work on a branch and make a pull request (PR) when ready.
 mention the issue it fixes in the PR.  You can say "fixes #1" and it will
mark issue #1 as fixed when you merge it.  This way people can look at the
whole fix to an issue, which becomes really important on larger projects.
Plus it's the expected workflow at most places.

Good to see you working through these :)

**Comment by laurengordonfahn** [comment]
Oh, crap, github, im so out of sync. I really just need to focus on my building. on it. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Adam Bozanich <notifications@github.com> Date: 1/16/17  2:06 PM  (GMT-08:00) To: laurengordonfahn/simple_notebook_project <simple_notebook_project@noreply.github.com> Cc: Lauren Gordon-Fahn <laurengordonfahn@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [laurengordonfahn/simple_notebook_project] More descriptive column names (#1) 
:) yes that's part of the point of going through this.



Next time do the work on a branch and make a pull request (PR) when ready.

 mention the issue it fixes in the PR.  You can say "fixes #1" and it will

mark issue #1 as fixed when you merge it.  This way people can look at the

whole fix to an issue, which becomes really important on larger projects.

Plus it's the expected workflow at most places.



Good to see you working through these :)







On Mon, Jan 16, 2017 at 1:51 PM, Lauren Gordon-Fahn <

**Comment by laurengordonfahn** [comment]
crap github, i forgot and brome the code :( with step two. I will get through it and branch and commit


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Adam Bozanich <notifications@github.com> Date: 1/16/17  2:06 PM  (GMT-08:00) To: laurengordonfahn/simple_notebook_project <simple_notebook_project@noreply.github.com> Cc: Lauren Gordon-Fahn <laurengordonfahn@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [laurengordonfahn/simple_notebook_project] More descriptive column names (#1) 
:) yes that's part of the point of going through this.



Next time do the work on a branch and make a pull request (PR) when ready.

 mention the issue it fixes in the PR.  You can say "fixes #1" and it will

mark issue #1 as fixed when you merge it.  This way people can look at the

whole fix to an issue, which becomes really important on larger projects.

Plus it's the expected workflow at most places.



Good to see you working through these :)







On Mon, Jan 16, 2017 at 1:51 PM, Lauren Gordon-Fahn <

**Comment by boz** [comment]
This is part of building it.  It'll become second nature soon :)

**Comment by laurengordonfahn** [comment]
In updating variable names learned at all levels at which variable name change can alter a project, from jinja templating, helper_functions, server, and javascript. It works as one.

**Comment by boz** [comment]
yeah it really underlines how everything is connected.  nice work!
