### ISSUE TITLE
Standard JSON representation of Note

### ISSUE THREAD

**Issue by boz** [laurengordonfahn/simple_notebook_project#2]
[add_note](https://github.com/laurengordonfahn/simple_notebook_project/blob/master/server.py#L28-L35) returns a JSON representation of the created note.  The field names should be similar to the database column names.

Change:

 - `"note_id"` -> `"id"`
 - `"note_title"` -> `"title"`

And so on, for all of the fields.

**Comment by laurengordonfahn** [comment]
Updated json representation variables to adhere to industry standard.
